### ISSUE TITLE
How would I add a JS file that registers multiple components?

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-registry#2]
https://github.com/ngokevin/aframe-physics-components/blob/master/dist/aframe-physics-components.js

This physics component is bundled up with `physics-body` and `physics-world`. They are coupled and are bundled with cannon.js.

**Comment by cvan** [comment]
I would turn `url` into `urls` and make it an array

**Comment by cvan** [comment]
Also, I think it might be nicer to turn this into an array of objects and have `slug` be a key. Or at the very least duplicate `slug`?

**Comment by donmccurdy** [comment]
Possible syntax:

```yaml
aframe-physics
  - name: physics-body
    versions:
      0.3.0:
        version: <version>
        path: <path>.min.js
  - name: physics-world
    versions:
      0.3.0:
        version: <version>
        path: <path>.min.js
```

Array of objects has the advantage that the name of each component is specified. 

But just bundling components may not be enough, similar cases could also include a system. `leap-hands` and `aframe-extras.physics`, for example.

**Comment by ngokevin** [comment]
That'd make sense. It'd still allow a one component per file, and we can perhaps in the future allow component packs depending on how things go.

**Comment by cvan** [comment]
[This is the format I used for Holodeck Club's `manifest.json`s.](https://github.com/holodeck-club/holodeck-club.github.io/blob/b35d76f/manifest.json#L17-L27)

I would suggest using the [unpkg (née npmcdn)](https://unpkg.com/#/) syntax (e.g., `https://unpkg.com/package@version/file`). You can read [these notes on the syntax](https://unpkg.com/).

```json
{
  "components": [
    "/common/assets/js/voice-controls.js",
    "aframe-href-component@0.5.1",
    "annyang",
    "donmccurdy/aframe-extras@master/src/primitives/a-ocean.js"
    "github:bryik/aframe-vive-cursor-component@master/aframe-vive-cursor-component.min.js",
    "github:nylki/aframe-lsystem-component",
    "https://holodeck.club/common/assets/js/lib/voice-nav.js",
    "maxkrieger/aframe-draw-component",
    "npm:mayognaise/aframe-video-shader@20.1.8"
  ]
}
```

Just some thoughts.

**Comment by ngokevin** [comment]
@donmccurdy your format looks good, i'm gonna start implementing it

**Comment by donmccurdy** [comment]
Great! That would be enough for me to pull a few components in from aframe-extras. Maybe `three-model` and `ply-model`. Can figure out systems another day. 🙂

**Comment by ngokevin** [comment]
For like the `ocean` component, you can either give it its own `package.json` + directory...or just build a dist within `aframe-extras`. Either way currently, needs a separate dist. Separate directory is preferred so we can give it its own README/preview image.

Yeah, need to think about systems since your physics isn't 1:1...(physics system <- body, joint, etc). It'd be awesome just to checkbox physics.

**Comment by donmccurdy** [comment]
👍 [i just extended my build script](https://github.com/donmccurdy/aframe-extras/commit/c560e0412574365fce953d92d6996c6af892f61a) to create dists for whitelisted components, that should fine work for ocean.

Will probably export physics to a repo, but still at least a couple components + a system involved yeah.

**Comment by ngokevin** [comment]
Need to figure out a way to match a component with a GitHub README hmm

**Comment by ngokevin** [comment]
@donmccurdy This seems doable:

```yaml
  aframe-physics:
    names: body, dynamic-body, static-body, joint
    versions:
      0.3.0:
        version: ^1.0.0
        path: dist/aframe-physics.min.js
```
