### ISSUE TITLE
Consider flattening structure to support other module types later (components, systems, primitives)

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-registry#28]
We could perhaps cross this road later once we consider support, but good to get feedback. This is easier than managing different aspects of a package across different keys. 

Current:

```
components:
  aframe-physics:
    names: body, joint
```

to:

```
aframe-physics:
  components: body, joint
  systems: physics
  primitives: a-newtons-cradle
```
