### ISSUE TITLE
Allow defining a single path rather than a path for each version

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-registry#39]
```
package:
  versions: 
    0.4.0: 
       version: x.x.x
       path: blahblah
```

```
package:
  path: blahblah
  versions: 
    0.4.0: 
       version: x.x.x
```

Path can be overridden by a version entry
